### PR TITLE
Update __init__.py (model import error)

### PR DESCRIPTION
**Pull request by yanliang3612**
## Thank you for sending a Pull Request to PyMeshLab!

On this repository, we keep two relevant branches:

- `main`: we keep here the **last release version of PyMeshLab**, with just bugfixes. In case of serious bugs caught after a release, this branch is used to publish "post-releases".
- `devel`: we add here new features and functionalities of the library that are going to appear in the next release of PyMeshLab. Bugfixes pushed in `main` are automatically merged on the `devel` branch.

Before submitting a PR, please check which branch suits better for your contribution!

**PLEASE REMOVE THIS BEFORE SUBMITTING**

### CODE REVIEW

**Comment by johnnynunez** [comment]
why is this not merged? @alemuntoni

**Comment by alemuntoni** [comment]
Is this useful at all??
What does it fix?

**Comment by johnnynunez** [comment]
> Is this useful at all?? What does it fix?

We have the error in last post1. I'm using last pymeshlab build

**Comment by alemuntoni** [comment]
How can I reproduce the error?
The built module library inside the `pymeshlab` directory is called `pmeshlab`, and therefore it should be imported correctly without errors.

**Comment by TimotF** [comment]
Seems to be linked to #373 

I got the same issue using a freshly install of python 3.9.13 on mac (apple silicon). If I install pymeshlab and try to just import it (tested inside and outside of a venv), I get this error.
Using this version make the `ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'` disappear, however I get another import error instead...

**Comment by alemuntoni** [comment]
> Seems to be linked to #373
> 
> I got the same issue using a freshly install of python 3.9.13 on mac (apple silicon). If I install pymeshlab and try to just import it (tested inside and outside of a venv), I get this error. Using this version make the `ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'` disappear, however I get another import error instead...

how are you installing pymeshlab? It is still not available for apple silicon from pip. It will from the next version.
And the error it could be caused by the fact that the version you installed was not built for apple silicon...

**Comment by TimotF** [comment]
I installed it using `pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab`

**Comment by alemuntoni** [comment]
> I installed it using `pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab`

That's not how pymeshlab is supposed to be installed.
The setup.py script must be run only when pymeshlab is already built and deployed.

**Comment by jarry-wang** [comment]
> > I installed it using `pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab`
> 
> That's not how pymeshlab is supposed to be installed. The setup.py script must be run only when pymeshlab is already built and deployed.

How to solve this problem? I encountered this issue while installing and starting ComfyUI-3D-Pack。
`  File "/Users/xxx/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 38, in <module>
    from .mesh_processer.mesh_utils import (
  File "/Users/xxx/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 7, in <module>
    import pymeshlab as pml
  File "/Users/xxx/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pymeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pymeshlab'`

I tried to change the 'from. pmeshlab import *' to 'from' in __init__. py import *， But some definitions are missing, 'PyMeshLabException' is not defined, name 'filter_list' is not defined， It seems that pmeshlab is still needed.
@alemuntoni @TimotF Has this problem been resolved later？

**Comment by alemuntoni** [comment]
> please，how to solve this problem? I encountered this issue while installing and starting ComfyUI-3D-Pack。
  File "/Users/xxx/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 38, in <module> from .mesh_processer.mesh_utils import ( File "/Users/xxx/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 7, in <module> import pymeshlab as pml File "/Users/xxx/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pymeshlab/__init__.py", line 11, in <module> from .pymeshlab import * ModuleNotFoundError: No module named 'pymeshlab.pymeshlab'
>
> I tried to change the from. pmeshlab import * to from . import *，but some definitions are missing, 'PyMeshLabException' is not defined, name 'filter_list' is not defined， It seems that pmeshlab is still needed.
@alemuntoni @TimotF Has this problem been resolved later？

I don't know how to solve the problem. But I'm pretty sure that this PR does not solve ANY problem at all.

When the `ModuleNotFoundError` happens, it means that the module cannot be loaded in your setup, and that could happen for any reason (different architecture from the one the package was built, missing basic library dependencies, such as opengl or an old libc, or just a conda environment that breaks everything). It is just impossible for me to help in these cases.

**Pull request closed without merging**
